
CC = g++

CFLAGS = -c -Wshadow -Winit-self -Wredundant-decls -Wcast-align -Wundef -Wfloat-equal -Winline -Wunreachable-code \
		 -Wmissing-declarations -Wmissing-include-dirs -Wswitch-enum -Wswitch-default -Weffc++ -Wmain -Wextra -Wall -g -pipe \
 		 -fexceptions -Wcast-qual -Wconversion -Wctor-dtor-privacy -Wempty-body -Wformat-security -Wformat=2 -Wignored-qualifiers \
		 -Wlogical-op -Wno-missing-field-initializers -Wnon-virtual-dtor -Woverloaded-virtual -Wpointer-arith -Wsign-promo \
		 -Wstack-usage=8192 -Wstrict-aliasing -Wstrict-null-sentinel -Wtype-limits -Wwrite-strings -Werror=vla -D_DEBUG \
		 -D_EJUDGE_CLIENT_SIDE

all: all

all: .\Spu\main.o .\Spu\Spu.o .\Stack\Stack.o 
	$(CC) .\Spu\main.o .\Spu\Spu.o .\Stack\Stack.o -o all

Spu.o: .\Spu\Spu.cpp
	$(CC) $(CFLAGS) .\Spu\Spu.cpp

Stack.o: .\Stack\Stack.cpp
	$(CC) $(CFLAGS) .\Stack\Stack.cpp

all.o: all.cpp
	$(CC) $(CFLAGS) all.cpp

clean:
	rm -rf *.o all



